### ISSUE TITLE
Support for Django 3

### ISSUE THREAD

**Issue by maltherd** [fsinfuhh/django-spectre-css#2]
Hello, thank you a lot, this project is great !
Saved me hours of struggling with `django-crispy-forms`'s bloated code, trying to make a custom pack.

I noticed the project requires Django<3, and that wouldn't do for me.
I simply git cloned and put the app inside my Django 3 project, and it works just fine.
Consider changing the requirement ?

Thanks for listening !

**Comment by Akasch** [comment]
As it only requires django<3 because i haven't tested it with django 3, I can Update it if it is working. I will update it in the next days.

**Comment by Akasch** [comment]
I have bumped it to Django<4.

If you have more missing features or problems feel free to do pull requests or open issues. I think there are some form elements or configurations missing or poorly implemented at the moment.

**Comment by maltherd** [comment]
I noticed with a new install that, from Django 3.2 on, it is no longer allowed to have hyphens in a package name. It works with Django 3.0.x and 3.1.x though, which led me to make this issue originally.

The error raised : 
```
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: The app label 'django-spectre-css' is not a valid Python identifier.
```
See this related issue comment for a potential solution https://github.com/FortAwesome/Font-Awesome/issues/17801#issuecomment-817929169 

Thanks for your work !
