### ISSUE TITLE
The app label 'django-spectre-css' is not a valid Python identifier.

### ISSUE THREAD

**Issue by maltherd** [fsinfuhh/django-spectre-css#6]
I noticed with a new install that, from Django 3.2 on, it is no longer allowed to have hyphens in a package name. It works with Django 3.0.x and 3.1.x though, which led me to make #2 originally, thinking it would keep working.

The error raised : 
```
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: The app label 'django-spectre-css' is not a valid Python identifier.
```
See this related issue comment for a potential solution https://github.com/FortAwesome/Font-Awesome/issues/17801#issuecomment-817929169 

Thanks for your work !

_Originally posted by @maltherd in https://github.com/fsinfuhh/django-spectre-css/issues/2#issuecomment-1002744041_

**Comment by Akasch** [comment]
Fixed in #7, a new release will be done shortly. A Change in Django Settings is necessary.
